enum Cartouche {
  BLUE = "BLUE",
  RED = "RED",
  GOLD = "GOLD",
}

export const pokemons = [
  {
    id: 1,
    name: "Dracofeu",
    type: "Fire",
    cartouche: Cartouche.BLUE,
  },
  {
    id: 2,
    name: "Bulbizar",
    type: "Grass",
    cartouche: Cartouche.BLUE,
  },
  {
    id: 3,
    name: "Elektor",
    type: "Lightning",
    cartouche: Cartouche.BLUE,
  },
  {
    id: 4,
    name: "Feunard",
    type: "Fire",
    cartouche: Cartouche.GOLD,
  },
  {
    id: 4,
    name: "Feunard",
    type: "Fire",
    cartouche: Cartouche.GOLD,
  },
  { id: 5, name: "Aipom", type: "Normal", cartouche: Cartouche.RED },
  { id: 6, name: "Alakazam", type: "Psychic", cartouche: Cartouche.RED },
  { id: 7, name: "Alcremie", type: "Fairy", cartouche: Cartouche.RED },
  { id: 8, name: "Alomomola", type: "Water", cartouche: Cartouche.RED },
  { id: 9, name: "Ambipom", type: "Normal", cartouche: Cartouche.RED },
  { id: 10, name: "Ampharos", type: "Electric", cartouche: Cartouche.RED },
  { id: 11, name: "Arbok", type: "Poison", cartouche: Cartouche.RED },
  { id: 12, name: "Arcanine", type: "Fire", cartouche: Cartouche.RED },
  { id: 13, name: "Arceus", type: "Normal", cartouche: Cartouche.RED },
  { id: 14, name: "Aromatisse", type: "Fairy", cartouche: Cartouche.RED },
  { id: 15, name: "Arrokuda", type: "Water", cartouche: Cartouche.RED },
  { id: 16, name: "Audino", type: "Normal", cartouche: Cartouche.RED },
  { id: 17, name: "Avalugg", type: "Ice", cartouche: Cartouche.RED },
  { id: 18, name: "Axew", type: "Dragon", cartouche: Cartouche.RED },
  { id: 19, name: "Azelf", type: "Psychic", cartouche: Cartouche.RED },
  { id: 20, name: "Azumarill", type: "Fairy", cartouche: Cartouche.RED },
  { id: 21, name: "Azurill", type: "Fairy", cartouche: Cartouche.RED },
  { id: 22, name: "Ivysaur", type: "Water", cartouche: Cartouche.BLUE },
  { id: 23, name: "Venusaur", type: "Water", cartouche: Cartouche.BLUE },
  { id: 24, name: "Charmander†", type: "Water", cartouche: Cartouche.BLUE },
  { id: 25, name: "Charmeleon", type: "Water", cartouche: Cartouche.BLUE },
  { id: 26, name: "Charizard", type: "Water", cartouche: Cartouche.BLUE },
  { id: 27, name: "Squirtle", type: "Water", cartouche: Cartouche.BLUE },
  { id: 28, name: "Wartortle", type: "Water", cartouche: Cartouche.BLUE },
  { id: 29, name: "Blastoise", type: "Water", cartouche: Cartouche.BLUE },
  { id: 30, name: "Caterpie", type: "Water", cartouche: Cartouche.BLUE },
  { id: 31, name: "Metapod", type: "Water", cartouche: Cartouche.BLUE },
  { id: 32, name: "Butterfree", type: "Water", cartouche: Cartouche.BLUE },
  { id: 33, name: "Weedle", type: "Water", cartouche: Cartouche.BLUE },
  { id: 34, name: "Kakuna", type: "Water", cartouche: Cartouche.BLUE },
  { id: 35, name: "Beedrill", type: "Water", cartouche: Cartouche.BLUE },
  { id: 36, name: "Pidgey", type: "Water", cartouche: Cartouche.BLUE },
  { id: 37, name: "Pidgeotto", type: "Water", cartouche: Cartouche.BLUE },
  { id: 38, name: "Pidgeot", type: "Water", cartouche: Cartouche.BLUE },
  { id: 39, name: "Rattata", type: "Water", cartouche: Cartouche.BLUE },
  { id: 40, name: "Raticate", type: "Water", cartouche: Cartouche.BLUE },
  { id: 41, name: "Spearow", type: "Water", cartouche: Cartouche.BLUE },
  { id: 42, name: "Fearow", type: "Water", cartouche: Cartouche.BLUE },
  { id: 43, name: "Ekans", type: "Water", cartouche: Cartouche.BLUE },
  { id: 44, name: "Arbok", type: "Water", cartouche: Cartouche.BLUE },
  { id: 45, name: "Pikachudagger", type: "Water", cartouche: Cartouche.BLUE },
  { id: 46, name: "Raichu", type: "Water", cartouche: Cartouche.BLUE },
  { id: 47, name: "Sandshrew", type: "Water", cartouche: Cartouche.BLUE },
  { id: 48, name: "Sandslash", type: "Water", cartouche: Cartouche.BLUE },
  { id: 49, name: "Nidoran♀", type: "Water", cartouche: Cartouche.BLUE },
  { id: 50, name: "Nidorina", type: "Water", cartouche: Cartouche.BLUE },
];

export const dresseurs = [
  {
    id: 1,
    name: "Sacha",
    pokemons: [pokemons[1], pokemons[0], pokemons[3]],
  },
  {
    id: 2,
    name: "Jean",
    pokemons: [pokemons[3], pokemons[5], pokemons[1]],
  },
];
